# Generated by Django 4.1 on 2022-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('admin', models.BooleanField(default=False)),
                ('genre_pref', models.CharField(max_length=50)),
                ('user_biography', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
