# Generated by Django 4.1.1 on 2022-09-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_options_alter_user_genre_pref_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
