# Generated by Django 4.1.3 on 2022-11-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="cod_book",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="cod_user",
            new_name="user",
        ),
    ]
