# Generated by Django 4.1.1 on 2022-09-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_email_remove_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="genre_pref",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name_user",
        ),
    ]
