# Generated by Django 4.1.1 on 2022-09-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_user_admin_remove_user_genre_pref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cod_user",
            field=models.IntegerField(default=0),
        ),
    ]
