# Generated by Django 4.1.3 on 2022-12-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_cod_book_review_book_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(max_length=100)),
                ("text", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_forms", models.CharField(max_length=100)),
                (
                    "cod_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Forms",
            },
        ),
        migrations.CreateModel(
            name="Resolves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DTH", models.DateTimeField(blank=True)),
                (
                    "cod_forms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.form"
                    ),
                ),
                (
                    "cod_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resolve",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("genres", models.CharField(max_length=100)),
                (
                    "answer",
                    models.ManyToManyField(
                        related_name="answer_question", to="core.answer"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AddField(
            model_name="form",
            name="question",
            field=models.ManyToManyField(
                related_name="form_question", to="core.question"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="user",
            field=models.ManyToManyField(
                related_name="resolve", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
