# Generated by Django 4.1.3 on 2022-12-01 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_answer_form_resolves_question_form_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerAssociativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.answer"
                    ),
                ),
                (
                    "cod_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.question"
                    ),
                ),
                (
                    "cod_resp_forms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AnswerAssociativa",
            },
        ),
    ]
