# Generated by Django 4.1.3 on 2022-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_answerassociativa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="status",
            field=models.IntegerField(),
        ),
    ]
