# Generated by Django 4.1.3 on 2022-12-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_answer_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="user",
        ),
    ]
