# Generated by Django 4.1.3 on 2022-12-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_form_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resolves",
            options={"verbose_name_plural": "Resolves"},
        ),
    ]
