# Generated by Django 4.1.3 on 2022-12-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_resolves_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
    ]
