# Generated by Django 4.1.3 on 2022-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_question_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="genres",
        ),
        migrations.AddField(
            model_name="question",
            name="genres",
            field=models.ManyToManyField(related_name="genres", to="core.genre"),
        ),
    ]
