# Generated by Django 4.1.3 on 2022-12-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_question_genres_question_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerassociativa",
            name="cod_forms",
            field=models.ManyToManyField(related_name="cod_forms", to="core.form"),
        ),
    ]
