# Generated by Django 4.1.3 on 2022-12-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_answerassociativa_cod_forms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="name_forms",
        ),
        migrations.AddField(
            model_name="form",
            name="cod_form",
            field=models.IntegerField(null=True),
        ),
    ]
