# Generated by Django 4.1.3 on 2022-12-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_form_name_forms_form_cod_form"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="cod_form",
            new_name="name_forms",
        ),
    ]
