# Generated by Django 4.1.3 on 2022-12-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_book_link_book_price"),
        ("core", "0014_rename_cod_form_form_name_forms"),
    ]

    operations = []
